[package]
name = "cordis-plugin-timer"
description = "Cordis timer plugin: timeout/interval/throttle/debounce"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
cordis-core = { path = "../cordis-core" }
parking_lot.workspace = true
tokio.workspace = true

[dev-dependencies]
tokio = { workspace = true, features = ["test-util"] }
