//! Procedural macros for the Cordis framework.
//!
//! - `#[service]` on a struct generates the `Service` impl (stable name), a
//!   typed accessor extension trait (`ctx.foo()`) and a traced call handle
//!   (`FooHandle`) that carries the access-point context. The accessor is
//!   implemented for both `Context` and `ShadowContext`; on a
//!   `ShadowContext` the lookup resolves through the service's own shadow
//!   scope, matching `this.ctx[name]` in the TS reference.
//! - `#[service]` on an *inherent impl block* generates forwarding methods on
//!   the handle: every `pub` instance method is forwarded, and a leading
//!   `&ShadowContext` parameter is consumed by the handle (its traced context
//!   is injected automatically). Methods marked `#[no_forward]`, private
//!   methods and non-`&self` methods are not forwarded.

use proc_macro::TokenStream;
use proc_macro2::TokenStream as TokenStream2;
use quote::{format_ident, quote};
use syn::{DeriveInput, FnArg, ImplItem, ItemImpl, Receiver, Type, Visibility, parse2};

fn to_snake_case(ident: &syn::Ident) -> String {
    let name = ident.to_string();
    let mut out = String::new();
    for (index, ch) in name.chars().enumerate() {
        if ch.is_uppercase() {
            if index > 0 {
                out.push('_');
            }
            out.push(ch.to_ascii_lowercase());
        } else {
            out.push(ch);
        }
    }
    out
}

/// Whether the attribute is `#[no_forward]`.
fn is_no_forward(attr: &syn::Attribute) -> bool {
    attr.path()
        .segments
        .last()
        .map(|segment| segment.ident == "no_forward")
        .unwrap_or(false)
}

/// Whether the type is `&ShadowContext` (any path ending in `ShadowContext`).
fn is_shadow_ctx(ty: &Type) -> bool {
    if let Type::Reference(reference) = ty
        && let Type::Path(path) = reference.elem.as_ref()
    {
        return path
            .path
            .segments
            .last()
            .map(|segment| segment.ident == "ShadowContext")
            .unwrap_or(false);
    }
    false
}

fn expand_struct(input: DeriveInput) -> TokenStream2 {
    let name = &input.ident;
    let vis = &input.vis;
    let snake = to_snake_case(name);
    let ext_trait = format_ident!("{}ServiceExt", name);
    let method = format_ident!("{}", snake);
    let handle = format_ident!("{}Handle", name);
    let context = quote!(::cordis_core::Context);
    let shadow = quote!(::cordis_core::ShadowContext);
    let service_name = quote!(<#name as ::cordis_core::Service>::NAME);
    let expanded = quote! {
        #input

        impl ::cordis_core::Service for #name {
            const NAME: &'static str = #snake;
        }

        /// Traced call handle for the service.
        ///
        /// Created by the typed accessor at the access point: it carries
        /// the service instance and the traced
        /// `ShadowContext` captured there.
        /// Forwarded methods (generated by `#[service]` on the impl block)
        /// inject the context automatically, so dependency reads resolve in
        /// the service's own scope while effects, plugins and fiber
        /// operations follow the caller's scope — mirroring the TS
        /// traceable `this.ctx`. The fields are public as the explicit
        /// escape hatch for callers that bypass the traced path.
        #vis struct #handle {
            /// The underlying service instance.
            pub service: std::rc::Rc<#name>,
            /// The traced context captured at the access point.
            pub ctx: #shadow,
        }

        impl #handle {
            /// The underlying service instance.
            pub fn service(&self) -> &std::rc::Rc<#name> {
                &self.service
            }

            /// The traced context captured at the access point.
            pub fn ctx(&self) -> &#shadow {
                &self.ctx
            }

            /// Invokes a closure with the service and its traced context.
            ///
            /// This is the universal fallback for methods the macro does not
            /// forward (exotic signatures): the context still comes from the
            /// handle, never from the caller.
            pub fn call_with<R>(&self, f: impl FnOnce(&#name, &#shadow) -> R) -> R {
                f(&self.service, &self.ctx)
            }
        }

        impl std::ops::Deref for #handle {
            type Target = #name;

            fn deref(&self) -> &#name {
                &self.service
            }
        }

        /// Typed accessor for the service.
        #vis trait #ext_trait {
            /// Returns a traced handle for the service registered on this
            /// context, if any. On a
            /// `ShadowContext` the lookup
            /// uses the service's own scope (the shadow); on a
            /// `Context` it uses the context's own
            /// scope.
            fn #method(&self) -> Option<#handle>;
        }

        impl #ext_trait for #context {
            fn #method(&self) -> Option<#handle> {
                let service = self.get::<#name>()?;
                let own = self.shadow_of(#service_name).map(|entry| entry.ctx)?;
                Some(#handle {
                    service,
                    ctx: #shadow::new(own, self.clone()),
                })
            }
        }

        impl #ext_trait for #shadow {
            fn #method(&self) -> Option<#handle> {
                let service = self.get::<#name>()?;
                let own = self.shadow_of(#service_name).map(|entry| entry.ctx)?;
                Some(#handle {
                    service,
                    ctx: #shadow::new(own, self.caller().clone()),
                })
            }
        }
    };
    expanded
}

fn build_forwarder(method: &syn::ImplItemFn) -> Option<TokenStream2> {
    let signature = &method.sig;
    // Only public `&self` instance methods are forwarded.
    if !matches!(method.vis, Visibility::Public(_)) {
        return None;
    }
    if method.attrs.iter().any(is_no_forward) {
        return None;
    }
    if !matches!(
        signature.receiver(),
        Some(Receiver {
            reference: Some(_),
            mutability: None,
            ..
        })
    ) {
        return None;
    }

    let name = &signature.ident;
    let vis = &method.vis;
    let asyncness = &signature.asyncness;
    let unsafety = &signature.unsafety;
    let generics = &signature.generics;
    let output = &signature.output;
    let attrs: Vec<_> = method
        .attrs
        .iter()
        .filter(|attr| !is_no_forward(attr))
        .collect();

    // The leading `&ShadowContext` parameter is consumed by the handle;
    // every other parameter is forwarded as-is.
    let mut consumed = false;
    let mut inputs = Vec::new();
    let mut args = Vec::new();
    for argument in signature.inputs.iter().skip(1) {
        match argument {
            FnArg::Typed(typed) => {
                if !consumed && inputs.is_empty() && is_shadow_ctx(&typed.ty) {
                    consumed = true;
                } else {
                    inputs.push(argument.clone());
                    args.push(typed.pat.as_ref().clone());
                }
            }
            FnArg::Receiver(_) => return None,
        }
    }
    let call_args = if consumed {
        quote!(&self.ctx, #(#args),*)
    } else {
        quote!(#(#args),*)
    };

    // Explicit turbofish for generic type/const parameters (lifetimes are
    // inferred).
    let turbofish = {
        let params: Vec<_> = generics
            .type_params()
            .map(|param| param.ident.clone())
            .chain(generics.const_params().map(|param| param.ident.clone()))
            .collect();
        if params.is_empty() {
            quote!()
        } else {
            quote!(::<#(#params),*>)
        }
    };
    let await_kw = if signature.asyncness.is_some() {
        quote!(.await)
    } else {
        quote!()
    };

    Some(quote! {
        #(#attrs)*
        #vis #unsafety #asyncness fn #name #generics (&self, #(#inputs),*) #output {
            self.service.#name #turbofish (#call_args) #await_kw
        }
    })
}

fn expand_impl(input: ItemImpl) -> TokenStream2 {
    // Trait impls (e.g. `impl Debug for Foo`) are left untouched.
    if input.trait_.is_some() {
        return quote!(#input);
    }
    let name = match input.self_ty.as_ref() {
        Type::Path(path) => match path.path.segments.last() {
            Some(segment) => segment.ident.clone(),
            None => return quote!(compile_error!("#[service] impl requires a plain type name")),
        },
        _ => return quote!(compile_error!("#[service] impl requires a plain type name")),
    };
    let handle = format_ident!("{}Handle", name);

    // Re-emit the original impl with `#[no_forward]` markers stripped.
    let mut original = input.clone();
    for item in &mut original.items {
        if let ImplItem::Fn(method) = item {
            method.attrs.retain(|attr| !is_no_forward(attr));
        }
    }

    let mut forwarders = Vec::new();
    for item in &input.items {
        if let ImplItem::Fn(method) = item
            && let Some(forwarder) = build_forwarder(method)
        {
            forwarders.push(forwarder);
        }
    }

    quote! {
        #original

        impl #handle {
            #(#forwarders)*
        }
    }
}

/// Generates the `Service` impl, a typed accessor with a traced handle, and
/// (on an inherent impl) handle forwarding methods.
#[proc_macro_attribute]
pub fn service(_attr: TokenStream, item: TokenStream) -> TokenStream {
    if let Ok(input) = parse2::<DeriveInput>(item.clone().into()) {
        if !matches!(input.data, syn::Data::Struct(_)) {
            return quote!(compile_error!(
                "#[service] only supports structs and inherent impls"
            ))
            .into();
        }
        return expand_struct(input).into();
    }
    if let Ok(input) = parse2::<ItemImpl>(item.clone().into()) {
        return expand_impl(input).into();
    }
    quote!(compile_error!(
        "#[service] only supports structs and inherent impls"
    ))
    .into()
}

/// Marker for injection callbacks (see module docs).
#[proc_macro_attribute]
pub fn inject(_attr: TokenStream, item: TokenStream) -> TokenStream {
    item
}
